version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - apt-get update && apt-get -y install zip jq python3-pip && pip3 install --upgrade awscli
  pre_build:
    on-failure: ABORT
    commands:
      - echo No prebuild step
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo Building project dependencies
  post_build:
    on-failure: ABORT
    commands:
      - echo Updating Layer Function...